# Form implementation generated from reading ui file '/Users/huynhtanphat/Documents/Tu Duy Lap Trinh/UI/Primeevenod/UI/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/huynhtanphat/Documents/Tu Duy Lap Trinh/UI/Primeevenod/UI/../giaithua/images/IC_Avatar/309036_student_education_study_icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 0, 411, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(252, 1, 7);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 330, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.N = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.N.setGeometry(QtCore.QRect(160, 80, 113, 21))
        self.N.setObjectName("N")
        self.prime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.prime.setGeometry(QtCore.QRect(140, 170, 621, 61))
        self.prime.setReadOnly(True)
        self.prime.setObjectName("prime")
        self.even = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.even.setGeometry(QtCore.QRect(140, 250, 621, 61))
        self.even.setReadOnly(True)
        self.even.setObjectName("even")
        self.odd = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.odd.setGeometry(QtCore.QRect(140, 320, 621, 61))
        self.odd.setReadOnly(True)
        self.odd.setObjectName("odd")
        self.process = QtWidgets.QPushButton(parent=self.centralwidget)
        self.process.setGeometry(QtCore.QRect(280, 120, 113, 32))
        self.process.setObjectName("process")
        self.neww = QtWidgets.QPushButton(parent=self.centralwidget)
        self.neww.setGeometry(QtCore.QRect(410, 120, 113, 32))
        self.neww.setObjectName("neww")
        self.end = QtWidgets.QPushButton(parent=self.centralwidget)
        self.end.setGeometry(QtCore.QRect(540, 120, 113, 32))
        self.end.setObjectName("end")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.end.clicked.connect(MainWindow.close) # type: ignore
        self.neww.clicked.connect(self.N.clear) # type: ignore
        self.neww.clicked.connect(self.prime.clear) # type: ignore
        self.neww.clicked.connect(self.even.clear) # type: ignore
        self.neww.clicked.connect(self.odd.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Huỳnh Tấn Phát - K234111414"))
        self.label.setText(_translate("MainWindow", "PRIME, EVEN, ODD NUMBER!!!!!"))
        self.label_2.setText(_translate("MainWindow", "Input N:"))
        self.label_3.setText(_translate("MainWindow", "Prime Number:"))
        self.label_4.setText(_translate("MainWindow", "Even Number:"))
        self.label_5.setText(_translate("MainWindow", "Odd Number:"))
        self.process.setText(_translate("MainWindow", "Process"))
        self.neww.setText(_translate("MainWindow", "New"))
        self.end.setText(_translate("MainWindow", "End"))
